### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by rdev** [rdev/now-mobile#11]
This is an umbrella issue for the v1.1.0 release. Here's what's planned for this update:

**Features:**
- [x] Change username (#5)
- [x] Change team name
- [x] Delete team
- [x] Deployment details view (essentially `now inspect`)
- [x] Open deployment details view when opening app from Spotlight
- [x] Usage limit notification from background refresh (#7)
- [x] Re-steal user agent parsing and login message from Now Desktop (https://github.com/zeit/now-desktop/pull/509)

**Fixes**
- [x] Fix handling of empty avatars
- [x] Fix "Retry" button in `NetworkError`

**Comment by joao-alberto** [comment]
Hello @rdev your project is amazing!
Can I help with something? Maybe if you split this to do list in issues could be easier to track progress
Im would be happy to help doing some items from list

**Comment by rdev** [comment]
@joao-alberto Hi!
Yes, contributions are very welcome! :) 

I'm currently halfway through working on #7. Everything else is up for grabs :)
I'll create dedicated issues later. 

If you want to work on team editing/deletion, here's the design for it:

![screen shot 2018-08-09 at 02 55 19](https://user-images.githubusercontent.com/8418866/43858123-cb4ccb94-9b7f-11e8-8406-c259d4cb51d3.png)

There is no design for deployment details yet 😅

**Comment by joao-alberto** [comment]
Awesome! I'll work on it, these designs looks like are made in adobe xd, in right? Can you please share?

**Comment by rdev** [comment]
No, they’re made in Sketch. You can download the source [here](https://mobile.now.sh/#contributing).

**Comment by rdev** [comment]
General code for editing already exists in 
[1.1.0 branch](https://github.com/rdev/now-mobile/tree/1.1.0), we just need it to behave differently when `props.context.team` is set

**Comment by joao-alberto** [comment]
Fine, thanks @rdev I'll open PR soon

**Comment by rdev** [comment]
@joao-alberto my end is good to go. Waiting for your PR and we can release it 🙂

**Comment by joao-alberto** [comment]
@rdev Sorry for the delay, I was a little busy. Working on it now

**Comment by rdev** [comment]
@joao-alberto no rush, just letting you know :)
