### ISSUE TITLE
Broken `login` event on dashboard

### ISSUE THREAD

**Issue by evilrabbit** [rdev/now-mobile#27]
<img width="967" alt="screen shot 2018-08-18 at 10 16 19 pm" src="https://user-images.githubusercontent.com/6880091/44304526-5ab15c80-a334-11e8-8300-924aa96e3153.png">

**Comment by rdev** [comment]
@evilrabbit I’ve opened a [PR](
https://github.com/zeit/now-desktop/pull/511) in Now Desktop implementing this 🙂
