### ISSUE TITLE
Wrong aliases on team context

### ISSUE THREAD

**Issue by evilrabbit** [rdev/now-mobile#28]
As you can see on my screenshot I switched to ZEIT team (rigth top) - but the app is still showing my personal account aliases:

![image](https://user-images.githubusercontent.com/6880091/44304742-9c450600-a33a-11e8-940a-c40481a5e024.png)

**Comment by rdev** [comment]
What I suspect may have happened here is aliases request failed and it fell back on the last successful data fetch (this approach seemed like a good idea at the time before I implemented teams 😅)

But I'm not entirely sure that's what it was

**Comment by rdev** [comment]
Closing since this appears to be fixed on ZEIT’s end
